[project]
name = "learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nabeel Cryf T", email = "nabeel.cryf@mindster.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pandas>=3.0.6",
    "uvicorn>=0.53.0",
]

[project.scripts]
learning = "learning:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
